apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: cloud-orbit-frontend-ingress
 annotations:
   nginx.ingress.kubernetes.io/rewrite-target: /$2
   nginx.ingress.kubernetes.io/app-root: /frontend/
   cert-manager.io/cluster-issuer: lets-encrypt
   namespace: "{{ .Values.namespace }}"
spec:
 tls:
 - hosts:
   - {{ .Values.host }}
   secretName: cloud-orbit-frontend-ingress-tls
 rules:
 - host: {{ .Values.host }}
   http:
     paths:
     - backend:
         service:
           name: cloud-orbit-frontend-service
           port:
             number: 80
       path: /
       pathType: Prefix