apiVersion: v1
kind: Service
metadata:
  name: cloud-orbit-frontend-service
  namespace: "{{ .Values.namespace }}"
spec:
  selector:
    app: cloud-orbit-frontend
  type: ClusterIP
  # clusterIP: None
  ports:
    - name: cloud-orbit-frontend
      port: 80
      targetPort: 80
      protocol: TCP
