name: Upload Python Package

on:
  push:
    branches:
      - main
      - release/*
  workflow_dispatch:

jobs:
  test:
    name: Frontend Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build  -t ${{ secrets.DOCKERHUB_USERNAME }}/cloud-orbit-frontend-image microservice

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/cloud-orbit-frontend-image:latest